spring.application.name=auswendig-server

#---
# Spring Session Configuration (taken from: https://docs.spring.io/spring-session/reference/3.0/http-session.html#httpsession-jdbc-boot)

# Session store type.
spring.session.store-type=jdbc

# Session timeout. If a duration suffix is not specified, seconds are used.
server.servlet.session.timeout= 300m

# Database schema initialization mode. Per Copilot, this will cause Spring Session to create the SPRING_SESSION table, if it does not already exist.
spring.session.jdbc.initialize-schema=embedded

# Path to the SQL file to use to initialize the database schema.
# spring.session.jdbc.schema=classpath:org/springframework/session/jdbc/schema-@@platform@@.sql

# Name of the database table used to store sessions.
spring.session.jdbc.table-name=SPRING_SESSION

#---

# Database Connection
spring.datasource.url=jdbc:h2:mem:devdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=devuser
spring.datasource.password=password
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console